/**
 * Writes the compiled Rota ABI into the web package so the frontend has a
 * typed, checked-in copy without importing from contracts/artifacts.
 *
 *   npx hardhat run scripts/export-abi.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const artifact = resolve(
  here,
  "..",
  "artifacts",
  "contracts",
  "Rota.sol",
  "Rota.json",
);
const target = resolve(here, "..", "..", "web", "lib", "rota-abi.ts");

const { abi } = JSON.parse(readFileSync(artifact, "utf8"));

const body = `// Generated by contracts/scripts/export-abi.ts — do not edit by hand.
// Regenerate with: npm run export-abi --prefix contracts

export const ROTA_ABI = ${JSON.stringify(abi, null, 2)} as const;
`;

writeFileSync(target, body);
console.log(`wrote ${target} (${abi.length} ABI entries)`);
