/**
 * The Rota mark, as numbers.
 *
 * Eight seats on a circle: seven hollow, one solid. The solid seat is whose
 * turn it is. That is the whole idea of the product, so the mark is the idea
 * rather than a picture of one.
 *
 * Everything that draws the mark — the React component, app/icon.svg, the
 * Apple touch icon and the Open Graph card — reads its geometry from here, so
 * they cannot drift apart. app/icon.svg is a static file and cannot import,
 * so it is generated by scripts/gen-icon.ts from these same constants.
 */

/** Square drawing grid. One unit is one pixel when the mark renders at 32px. */
export const VIEW = 32;
export const CENTRE = VIEW / 2;

/** Radius of the circle the seats sit on. */
export const RING = 11;

export const SEATS = 8;

/**
 * Which seat is solid. Seat 0 is twelve o'clock and seats run clockwise, so
 * seat 1 is the top right: off-axis, which reads as mid-rotation. A solid dot
 * at twelve or three o'clock sits on an axis of symmetry and the mark goes
 * still.
 */
export const ACTIVE_SEAT = 1;

/** Hollow seats: the drawn radius, with the stroke straddling it. */
export const HOLLOW_R = 2.75;
export const STROKE = 1.5;

/**
 * The solid seat is drawn smaller than the hollow seats' outer edge
 * (3.25 against 2.75 + 0.75 = 3.5). Filled shapes read larger than outlined
 * ones of the same size, so matching them geometrically makes the solid dot
 * look swollen. Six percent off is the correction.
 */
export const SOLID_R = 3.25;

export type Seat = { x: number; y: number; r: number; solid: boolean };

/** Three decimals: enough that no rounding is visible at 512px. */
function round(n: number): number {
  return Math.round(n * 1000) / 1000;
}

/**
 * Seat centres, clockwise from twelve o'clock. y grows downwards in SVG, so
 * the cosine term is subtracted.
 */
export function seats(): Seat[] {
  return Array.from({ length: SEATS }, (_, i) => {
    const angle = (i / SEATS) * 2 * Math.PI;
    const solid = i === ACTIVE_SEAT;
    return {
      x: round(CENTRE + RING * Math.sin(angle)),
      y: round(CENTRE - RING * Math.cos(angle)),
      r: solid ? SOLID_R : HOLLOW_R,
      solid,
    };
  });
}

/**
 * How far the drawn mark reaches from the centre, stroke included. The
 * hollow seats reach furthest, not the solid one.
 */
export const EXTENT = RING + HOLLOW_R + STROKE / 2;

/**
 * The mark as a standalone SVG document.
 *
 * Needed as a string in two places that cannot render React: the static
 * app/icon.svg file, and the Open Graph and Apple icons, which are drawn by
 * satori — and satori does not render SVG elements, only an <img> pointing at
 * one. Both get their geometry from seats() above, so there is one mark.
 */
export function markSvg({
  colour = "currentColor",
  background,
  radius = 0,
  pad = 0,
  dark,
}: {
  /** Any CSS colour. Defaults to inheriting. */
  colour?: string;
  /** Omitted means transparent. */
  background?: string;
  /** Corner radius of the background plate, in grid units. */
  radius?: number;
  /** Extra breathing room around the mark, in grid units. */
  pad?: number;
  /**
   * Colour to switch to when the viewer's system is in dark mode. A favicon
   * is the one image nobody gets to place on a background of their choosing:
   * a near-black mark disappears on a dark tab strip. Safari and Firefox
   * honour a media query inside an SVG favicon; browsers that do not simply
   * keep the base colour, which is the current behaviour anyway.
   */
  dark?: string;
} = {}): string {
  const box = VIEW + pad * 2;
  const plate = background
    ? `<rect width="${box}" height="${box}" rx="${radius}" fill="${background}"/>`
    : "";
  const scheme = dark
    ? `<style>@media (prefers-color-scheme: dark){.ink{fill:${dark}}.ring{stroke:${dark}}}</style>`
    : "";
  const dots = seats()
    .map((s) =>
      s.solid
        ? `<circle class="ink" cx="${s.x + pad}" cy="${s.y + pad}" r="${s.r}" fill="${colour}"/>`
        : `<circle class="ring" cx="${s.x + pad}" cy="${s.y + pad}" r="${s.r}" fill="none" stroke="${colour}" stroke-width="${STROKE}"/>`,
    )
    .join("");
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${box} ${box}" width="${box}" height="${box}">${scheme}${plate}${dots}</svg>`;
}

/** For satori, which will only take an SVG through an <img> source. */
export function markDataUri(options?: Parameters<typeof markSvg>[0]): string {
  return `data:image/svg+xml;base64,${Buffer.from(markSvg(options)).toString("base64")}`;
}

/* ------------------------------------------------------------- wordmark */

/**
 * Oswald 700, measured in the browser against the face the app actually
 * loads — not taken from the foundry and not from a different instance.
 * Per em:
 *
 *   cap height        0.8125   (H, which has no overshoot)
 *   "ROTA" advance    2.1210
 *   left sidebearing  0.0469   (the R)
 *   right sidebearing 0.0198   (the A)
 *
 * The sidebearings matter: a lockup aligned on the text's advance box rather
 * than its ink sits visibly off-centre, because those two numbers differ by
 * more than 2% of an em.
 *
 * The weight matters too. app/layout.tsx loads Oswald at 500 and 700 only, so
 * asking for 600 gets silently served 700 — which is 2% wider and has a
 * different left sidebearing. Measuring a weight the page never loads is how
 * a lockup ends up mysteriously 1px out. 700 is also what the display
 * headlines use, so the wordmark costs no extra download.
 */
export const CAP_HEIGHT = 0.8125;
const ADVANCE = 2.121;
const LEFT_BEARING = 0.0469;
const RIGHT_BEARING = 0.0198;

/** The only Oswald weight this lockup may use. See the note above. */
export const WORD_WEIGHT = 700;

/** Cap height of ROTA, in mark grid units. Set against the mark's 29 of ink. */
export const WORD_SIZE = 24;
const CAP = WORD_SIZE * CAP_HEIGHT; // 19.5

/** Space between the mark's ink and the wordmark's ink. */
const GAP_X = 8;
/** Space between the mark's ink and the cap line, stacked. */
const GAP_Y = 7;

const INK_LEFT = WORD_SIZE * LEFT_BEARING;
const INK_WIDTH_UNTRACKED = WORD_SIZE * (ADVANCE - LEFT_BEARING - RIGHT_BEARING);

/**
 * Horizontal lockup. The box ends exactly on the A's ink, so centring the
 * lockup centres what you can see rather than a trailing letter-space.
 */
/** Where the wordmark's ink starts, in grid units from the box's left. */
export const WORD_INK_START = CENTRE + EXTENT + GAP_X; // 38.5

/**
 * Overall width of the horizontal lockup. The box ends exactly on the A's
 * ink, so centring the lockup centres what you can see rather than a
 * trailing letter-space.
 */
const LOCKUP_WIDTH = 92;

/**
 * Extra space added between each pair of letters, in grid units. Condensed
 * caps need the air. Exported because the Open Graph card sets tracking with
 * letter-spacing rather than textLength and has to arrive at the same
 * wordmark.
 */
export const TRACKING =
  (LOCKUP_WIDTH - WORD_INK_START - INK_WIDTH_UNTRACKED) / 3;

/**
 * Horizontal lockup: mark left, word right, cap height centred on the mark.
 *
 * Tracking is expressed as textLength rather than letter-spacing, which fixes
 * the wordmark's width whatever font is actually resolved — so a webfont
 * arriving late cannot make the lockup overflow its own box and clip.
 * lengthAdjust="spacing" moves the glyphs apart without distorting them,
 * across the three gaps between four letters, with nothing added after the
 * last.
 */
export const LOCKUP = {
  width: LOCKUP_WIDTH,
  height: VIEW,
  /** Cap-centred on the mark's centre. */
  baseline: CENTRE + CAP / 2,
  x: WORD_INK_START - INK_LEFT,
  textLength: WORD_SIZE * ADVANCE + TRACKING * 3,
};

/**
 * Stacked lockup: mark over wordmark, both on the same optical centre line.
 *
 * The mark is drawn larger here than in the horizontal lockup. Side by side,
 * a mark narrower than the word reads as a bullet in front of it and that is
 * correct; stacked above the word's full width, the same mark reads as an
 * ornament. Enlarging it to about three quarters of the word's width puts
 * them back on equal terms.
 */
export const MARK_SCALE = 1.4;

export const STACKED = (() => {
  const width = Math.round((LOCKUP_WIDTH - WORD_INK_START + 0.5) * 2) / 2; // 53.5
  const grid = VIEW * MARK_SCALE;
  const markInkBottom = (CENTRE + EXTENT) * MARK_SCALE;
  const capTop = markInkBottom + GAP_Y * MARK_SCALE;
  return {
    width,
    height: Math.ceil(capTop + CAP + WORD_SIZE * 0.02),
    scale: MARK_SCALE,
    /** Centres the scaled mark's grid on the box. */
    markOffset: (width - grid) / 2,
    baseline: capTop + CAP,
    /*
     * text-anchor="middle" centres the advance box, not the ink. The R's left
     * sidebearing is larger than the A's right one, so the visible word would
     * sit fractionally right of centre. Pull it back by half the difference.
     */
    x: width / 2 - (WORD_SIZE * (LEFT_BEARING - RIGHT_BEARING)) / 2,
    textLength: LOCKUP.textLength,
  };
})();
