// Generated by contracts/scripts/export-abi.ts — do not edit by hand.
// Regenerate with: npm run export-abi --prefix contracts

export const ROTA_ABI = [
  {
    "inputs": [
      {
        "internalType": "contract IERC20",
        "name": "usdc_",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [],
    "name": "AlreadyStarted",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "CircleComplete",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "member",
        "type": "address"
      }
    ],
    "name": "DuplicateMember",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "member",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "allowance",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "required",
        "type": "uint256"
      }
    ],
    "name": "InsufficientAllowanceToStart",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "caller",
        "type": "address"
      }
    ],
    "name": "NotAMember",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "timestamp",
        "type": "uint256"
      },
      {
        "internalType": "uint64",
        "name": "nextDueAt",
        "type": "uint64"
      }
    ],
    "name": "NotDue",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotStarted",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ReentrancyGuardReentrantCall",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "token",
        "type": "address"
      }
    ],
    "name": "SafeERC20FailedOperation",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "provided",
        "type": "uint256"
      }
    ],
    "name": "TooFewMembers",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "provided",
        "type": "uint256"
      }
    ],
    "name": "TooManyMembers",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "circleId",
        "type": "uint256"
      }
    ],
    "name": "UnknownCircle",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ZeroAddressMember",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ZeroContribution",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ZeroPeriod",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ZeroToken",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "circleId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "address[]",
        "name": "members",
        "type": "address[]"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "contribution",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "period",
        "type": "uint64"
      }
    ],
    "name": "CircleCreated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "circleId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "uint32",
        "name": "cycleIndex",
        "type": "uint32"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "recipient",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "totalPaid",
        "type": "uint256"
      }
    ],
    "name": "Disbursed",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "circleId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "nextDueAt",
        "type": "uint64"
      }
    ],
    "name": "Started",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "MAX_MEMBERS",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "circleId",
        "type": "uint256"
      }
    ],
    "name": "amountDue",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "circleCount",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address[]",
        "name": "members",
        "type": "address[]"
      },
      {
        "internalType": "uint256",
        "name": "contribution",
        "type": "uint256"
      },
      {
        "internalType": "uint64",
        "name": "period",
        "type": "uint64"
      }
    ],
    "name": "createCircle",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "circleId",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "circleId",
        "type": "uint256"
      }
    ],
    "name": "disburse",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "circleId",
        "type": "uint256"
      }
    ],
    "name": "getCircle",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "contribution",
        "type": "uint256"
      },
      {
        "internalType": "uint64",
        "name": "period",
        "type": "uint64"
      },
      {
        "internalType": "uint64",
        "name": "nextDueAt",
        "type": "uint64"
      },
      {
        "internalType": "uint32",
        "name": "cycleIndex",
        "type": "uint32"
      },
      {
        "internalType": "bool",
        "name": "started",
        "type": "bool"
      },
      {
        "internalType": "uint256",
        "name": "memberCount",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "circleId",
        "type": "uint256"
      }
    ],
    "name": "getMembers",
    "outputs": [
      {
        "internalType": "address[]",
        "name": "",
        "type": "address[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "circleId",
        "type": "uint256"
      }
    ],
    "name": "isComplete",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "circleId",
        "type": "uint256"
      }
    ],
    "name": "previewRound",
    "outputs": [
      {
        "components": [
          {
            "internalType": "address",
            "name": "member",
            "type": "address"
          },
          {
            "internalType": "uint256",
            "name": "allowance",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "balance",
            "type": "uint256"
          },
          {
            "internalType": "bool",
            "name": "ready",
            "type": "bool"
          }
        ],
        "internalType": "struct Rota.MemberStatus[]",
        "name": "statuses",
        "type": "tuple[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "circleId",
        "type": "uint256"
      }
    ],
    "name": "start",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "usdc",
    "outputs": [
      {
        "internalType": "contract IERC20",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;
